version: 2.6.{build}
branches:
  only:
  - master
max_jobs: 1
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0-pre'
build:
  verbosity: minimal